name: fixcore
channels:
  - conda-forge
  - defaults
  - bioconda
  - chrisjackson-pellicle
dependencies: 
  - python
  - biopython==1.81
  - pandas==2.0.3
  - pip
  - seqkit==2.8.2
  - snp-sites==2.5.1
  - mafft=7.526
  - python>=3.5
  - pip==24.2
  - amas==1.0
  - iqtree==2.3.6
  - snp-sites==2.5.1
  - snp-dists==0.8.2
  - r-base=4.4.1
  - r-tidyverse==2.0.0
  - r-ape==5.8
  - r-phangorn==2.12.1
  - r-phylobase==0.8.12
  - r-logger==0.3.0
  - trimal=1.5.0
  - seqtk==1.4
  - clipkit=2.3.0
  - treeshrink=1.3.9
  - hmmcleaner
