name: comparisions
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies: 
  - biopython==1.81
  - pandas==2.0.3
  - pip
  - seqkit==2.8.2
  - mafft=7.526
  - python>=3.5
  - pip==24.2
  - amas==1.0
  - iqtree==2.3.6
  - snp-sites==2.5.1
  - snp-dists==0.8.2
  - seqtk==1.4
  - parallel